@startuml tws
entity product{
    *id : INT (PK)
    --
    name_product : (VARCHAR)
    code_product : (VARCHAR)
    image : (VARCHAR)
    id_category : (FK)
}


entity category{
    *id : INT (PK)
    --
    name_categoty : (VARCHAR)
}

entity detailproduct{
    *id : INT (PK)
    --
    id_product : (FK)
    id_detail : (FK)
}

entity detail{
    *id : INT (PK)
    --
    short_description : (TINYTEXT)
    long_description : (LONGTEXT)
}

product }|--|{ category
detailproduct }|--|| product
detailproduct }|--|| detail
@enduml